# Generated by Django 5.1.2 on 2026-03-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, verbose_name='Краткий пересказ')),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
